name: Setup PHP

description: Setup PHP build

inputs:
    php-version:
        description: 'PHP version to use, default to 8.0'
        required: false
        default: '8.0'

runs:
    using: composite
    steps:
        -   name: Install PHP
            uses: shivammathur/setup-php@v2
            with:
                php-version: ${{ inputs.php-version }}

        -   id: get-composer-cache-directory
            name: Get Composer caches directory path
            run: echo "dir=$(php composer.phar config cache-files-dir)" >> $GITHUB_OUTPUT
            shell: bash

        -   id: mount-cache-directory
            name: Mount cache directory
            uses: actions/cache@v3
            with:
                path: ${{ steps.get-composer-cache-directory.outputs.dir }}
                key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
                restore-keys: ${{ runner.os }}-composer-

        -   id: install-composer-dependencies
            name: Install composer dependencies
            run: php composer.phar install --ansi
            shell: bash
